# Generated by Django 5.2.9 on 2026-03-05 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proApp', '0011_wastecollectionrequest_collector_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request_feedback', to='proApp.wastecollectionrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proApp.userreg')),
            ],
        ),
    ]
