# Generated by Django 5.2.9 on 2026-03-05 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proApp', '0012_requestfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_feedback', to='proApp.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proApp.userreg')),
            ],
        ),
    ]
