# Generated by Django 5.2.9 on 2026-03-05 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proApp', '0013_orderfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
