# Generated by Django 5.2.9 on 2026-03-20 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proApp', '0014_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proApp.organizer'),
        ),
    ]
